import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "2ombe",
      email: "2ombe@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "bruce1",
      email: "bruce1@gmail.com",
      password: bcrypt.hashSync("123456"),
      suAdmin: true,
    },
    {
      name: "jullien",
      email: "jullien@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "john@gmail.com",
      password: bcrypt.hashSync("7890"),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: "1",
      izina: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "T-shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "NIKE",
      rating: 4,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
    {
      izina: "Nike slim pants",
      slug: "nike-slim-pants",
      category: "pants",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 0,
      brand: "NIKE",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
    {
      izina: "adidas slim shirt",
      pslug: "adidas-slim-shirt",
      category: "T-shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "adidas",
      rating: 1,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
    {
      //_id: "4",
      izina: "adidas slim pant",
      slug: "adida-slim-shirt",
      category: "T-shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "adidas",
      rating: 2.5,
      numReviews: 10,
      description: "high quality shirt",
      costPrice: 100,
    },
  ],
};

export default data;
